# Generated by Django 3.1.7 on 2021-03-19 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_item_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='image',
            field=models.ImageField(null=True, upload_to='itemss/'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
